development:
  secret_key_base: <%= Rails.application.credentials.dig(Rails.env.to_sym, :secret_key_base) %>
test:
  secret_key_base: <%= Rails.application.credentials.dig(Rails.env.to_sym, :secret_key_base) %>
production:
  secret_key_base: <%= Rails.application.credentials.dig(Rails.env.to_sym, :secret_key_base) %>
